"use server";

import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prismadb } from "@/lib/prisma";
import { logActivity } from "@/actions/audit";
import { BlobServiceClient } from "@azure/storage-blob";
import { getAiClient } from "@/lib/ai-helper";
import { generateText } from "ai";

/**
 * Downloads an image from a temporary URL (e.g. AI generator),
 * uploads it to persistent storage (Azure Blob),
 * and creates a MediaItem record.
 */
export async function saveGeneratedImage(
    tempUrl: string,
    prompt: string,
    metadata?: { title?: string; altText?: string; description?: string; caption?: string }
) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || !session.user) {
            throw new Error("Unauthorized");
        }

        // 1. Fetch the image data
        console.log("[SAVE_GENERATED_IMAGE] Fetching from:", tempUrl);
        const imageRes = await fetch(tempUrl);
        if (!imageRes.ok) {
            throw new Error(`Failed to fetch image from source: ${imageRes.statusText}`);
        }
        const arrayBuffer = await imageRes.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const size = buffer.length;
        const contentType = imageRes.headers.get("content-type") || "image/png";

        // 2. Upload to Azure Blob Storage
        const conn = process.env.BLOB_STORAGE_CONNECTION_STRING;
        const container = process.env.BLOB_STORAGE_CONTAINER;

        if (!conn || !container) {
            console.error("Azure Blob Storage not configured");
            throw new Error("Storage configuration missing");
        }

        // Generate a safe unique filename
        const timestamp = Date.now();
        const safePrompt = prompt.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "_");
        const extension = contentType.split("/")[1] || "png";
        const filename = `generated_${safePrompt}_${timestamp}.${extension}`;
        const key = `uploads/${(session.user as any).id}/${filename}`;

        const serviceClient = BlobServiceClient.fromConnectionString(conn);
        const containerClient = serviceClient.getContainerClient(container);
        const blobClient = containerClient.getBlockBlobClient(key);

        console.log("[SAVE_GENERATED_IMAGE] Uploading to Azure:", key);
        await blobClient.uploadData(buffer, {
            blobHTTPHeaders: { blobContentType: contentType },
        });

        const permanentUrl = blobClient.url;

        // 3. Generate SEO Metadata with AI (if valid provider available)
        let seoData = {
            title: metadata?.title || prompt.slice(0, 100),
            altText: metadata?.altText || prompt,
            caption: metadata?.caption || `Generated by AI with prompt: ${prompt}`,
            description: metadata?.description || "AI Generated Image",
        };

        try {
            console.log("[SAVE_GENERATED_IMAGE] Generating SEO metadata with AI...");
            // Use system/team AI client to analyze the image
            // We need a team ID. For now, we'll try to find the user's team or fallback to system default.
            // Since this is a server action, getting team ID might be tricky if not passed.
            // Assumption: Use the user's first team or a default system catch-all if possible.
            // Accessing user through prismadb to get teamId
            const user = await prismadb.users.findUnique({
                where: { id: (session.user as any).id },
                include: { assigned_team: true } // Relation is assigned_team, but looking at schema, teamUsers is not there.
            });

            // Re-checking schema: Users has 'team_id' and 'assigned_team'. It does NOT have 'teamUsers'.
            // The previous code used 'teamUsers', which is likely wrong based on the schema I just read?
            // Let's re-read the schema for Users model relations.

            // Users model has:
            // team_id String? @db.ObjectId
            // assigned_team Team? @relation(fields: [team_id], references: [id])

            // So getting teamId is direct: user.team_id

            const teamId = user?.team_id;

            if (teamId) {
                const { model } = await getAiClient(teamId);

                // Instruct AI to check the image content
                const systemPrompt = `You are an SEO expert. Analyze the visual content of this image. Provide a title, alt text, caption, and description. 
                Do NOT mention that it is AI-generated, digital art, or created by Nano Banana or any other tool. 
                Describe the subject matter as if it were a real photo or illustration.
                
                Format the output as a JSON object:
                {
                    "title": "Short title",
                    "altText": "Descriptive alt text for accessibility",
                    "caption": "Engaging caption",
                    "description": "Detailed description for SEO"
                }`;

                const { text } = await generateText({
                    model,
                    messages: [
                        {
                            role: 'user',
                            content: [
                                { type: 'text', text: systemPrompt },
                                { type: 'image', image: permanentUrl } // Pass the permanent URL which AI can access
                            ]
                        }
                    ]
                });

                // Parse JSON from text response
                // Simple regex to extract JSON if model wraps it in backticks
                const jsonMatch = text.match(/\{[\s\S]*\}/);
                if (jsonMatch) {
                    const parsed = JSON.parse(jsonMatch[0]);
                    seoData = {
                        title: parsed.title || seoData.title,
                        altText: parsed.altText || seoData.altText,
                        caption: parsed.caption || seoData.caption,
                        description: parsed.description || seoData.description,
                    };
                    console.log("[SAVE_GENERATED_IMAGE] AI SEO generation successful");
                }
            }
        } catch (aiError) {
            console.warn("[SAVE_GENERATED_IMAGE] AI SEO generation failed, falling back to basic metadata:", aiError);
            // Fallback is already set in initial seoData definition
        }

        // 4. Create MediaItem Record
        const mediaItem = await (prismadb as any).mediaItem.create({
            data: {
                url: permanentUrl,
                filename: filename,
                mimeType: contentType,
                size: size,
                width: 1024,
                height: 1024,
                title: seoData.title,
                caption: seoData.caption,
                altText: seoData.altText,
                description: seoData.description,
                userId: (session.user as any).id,
            },
        });

        await logActivity("Generated Media", "Media", `Saved AI image: ${filename}`);

        return {
            success: true,
            mediaItem,
            url: permanentUrl
        };

    } catch (error: any) {
        console.error("[SAVE_GENERATED_IMAGE] Error:", error);
        return {
            success: false,
            error: error.message
        };
    }
}
