"use client";

import { useState, useEffect, useRef } from "react";
import NextImage from "next/image";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Loader2, Sparkles, RefreshCw, Check } from "lucide-react";
import { toast } from "sonner";
import { generateNanoBananaImage } from "@/actions/cms/generate-nano-banana-image";
import { saveGeneratedImage } from "@/actions/cms/save-generated-image";
import { cn } from "@/lib/utils";

interface NanoBananaImageModalProps {
    isOpen: boolean;
    onClose: () => void;
    onImageSelect: (imageUrl: string) => void;
    initialPrompt?: string;
}

export function NanoBananaImageModal({
    isOpen,
    onClose,
    onImageSelect,
    initialPrompt = ""
}: NanoBananaImageModalProps) {
    const [prompt, setPrompt] = useState(initialPrompt);
    const [isGenerating, setIsGenerating] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);

    const prevInitialPrompt = useRef(initialPrompt);

    // Update prompt when modal opens with new initialPrompt
    useEffect(() => {
        if (isOpen && initialPrompt) {
            // If the initialPrompt has effectively changed, update local state
            if (initialPrompt !== prevInitialPrompt.current) {
                setPrompt(initialPrompt);
                setGeneratedImage(null);
                prevInitialPrompt.current = initialPrompt;
            } else if (!prompt) {
                // Also ensure we set it if prompt is empty (initial load case)
                setPrompt(initialPrompt);
            }
        }
    }, [isOpen, initialPrompt, prompt]);

    // SEO State
    const [showSeo, setShowSeo] = useState(false);
    const [seoData, setSeoData] = useState({
        title: "",
        altText: "",
        caption: "",
        description: "",
    });

    const handleGenerate = async () => {
        if (!prompt) return;

        try {
            setIsGenerating(true);
            const result = await generateNanoBananaImage(prompt, "blog");

            if (result && result.url) {
                setGeneratedImage(result.url);
                toast.success("Image generated successfully!");
                setSeoData({
                    title: prompt.slice(0, 50),
                    altText: prompt,
                    caption: `AI generated image: ${prompt}`,
                    description: "Generated by Nano Banana",
                });
            } else {
                toast.error("Failed to generate image. Please try again.");
            }
        } catch (error) {
            console.error("Generation error:", error);
            toast.error("Something went wrong during generation.");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleConfirm = async () => {
        if (!generatedImage) return;

        try {
            setIsSaving(true);
            toast.info("Saving to Media Library...");

            const result = await saveGeneratedImage(generatedImage, prompt, seoData);

            if (result.success && result.url) {
                onImageSelect(result.url);
                toast.success("Image saved to Media Library!");
                onClose();
            } else {
                toast.error(`Failed to save image: ${result.error}`);
            }
        } catch (error) {
            toast.error("An unexpected error occurred while saving.");
            console.error(error);
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-[700px] bg-[#0F1115] border-white/10 text-white p-0 overflow-hidden gap-0">
                <div className="grid grid-cols-1 md:grid-cols-2 h-full min-h-[400px]">
                    {/* Preview Side */}
                    <div className="bg-black/50 p-6 flex items-center justify-center border-b md:border-b-0 md:border-r border-white/10 relative group">
                        {generatedImage ? (
                            <div className="relative w-full aspect-square rounded-lg overflow-hidden border border-white/10 shadow-2xl">
                                <NextImage
                                    src={generatedImage}
                                    alt="Generated preview"
                                    fill
                                    className="object-contain bg-slate-900"
                                    unoptimized
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-4">
                                    <p className="text-xs text-white/80 line-clamp-2">{prompt}</p>
                                </div>
                            </div>
                        ) : (
                            <div className="text-slate-500 flex flex-col items-center gap-2">
                                <Sparkles className="h-8 w-8 opacity-20" />
                                <span>Preview will appear here</span>
                            </div>
                        )}
                    </div>

                    {/* Controls Side */}
                    <div className="p-6 flex flex-col h-full">
                        <DialogHeader className="mb-4">
                            <DialogTitle className="flex items-center gap-2 text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-yellow-400 to-orange-500">
                                <Sparkles className="h-5 w-5 text-yellow-500" />
                                Nano Banana AI
                            </DialogTitle>
                        </DialogHeader>

                        <div className="flex-1 space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="prompt">Image Prompt</Label>
                                <div className="relative">
                                    <textarea
                                        id="prompt"
                                        className="w-full min-h-[100px] bg-slate-950 border-white/10 rounded-md p-3 text-sm focus:ring-yellow-500/50 focus:border-yellow-500 resize-none"
                                        placeholder="Describe the image you want to generate..."
                                        value={prompt}
                                        onChange={(e) => setPrompt(e.target.value)}
                                    />
                                </div>
                            </div>

                            {/* SEO Optimizations */}
                            {generatedImage && (
                                <div className="space-y-3 pt-2 border-t border-white/10">
                                    <div className="flex items-center justify-between">
                                        <label className="text-xs font-medium text-slate-400">SEO Metadata</label>
                                        <button
                                            onClick={() => setShowSeo(!showSeo)}
                                            className={cn("text-[10px] px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors", showSeo && "bg-blue-900/50 text-blue-300")}
                                        >
                                            {showSeo ? "Hide" : "Edit"}
                                        </button>
                                    </div>

                                    {showSeo && (
                                        <div className="space-y-2 animate-in fade-in slide-in-from-top-1">
                                            <Input
                                                placeholder="Title"
                                                value={seoData.title}
                                                onChange={(e) => setSeoData({ ...seoData, title: e.target.value })}
                                                className="h-8 text-xs bg-slate-950 border-white/10"
                                            />
                                            <Input
                                                placeholder="Alt Text"
                                                value={seoData.altText}
                                                onChange={(e) => setSeoData({ ...seoData, altText: e.target.value })}
                                                className="h-8 text-xs bg-slate-950 border-white/10"
                                            />
                                            <Input
                                                placeholder="Short Description"
                                                value={seoData.description}
                                                onChange={(e) => setSeoData({ ...seoData, description: e.target.value })}
                                                className="h-8 text-xs bg-slate-950 border-white/10"
                                            />
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>

                        <DialogFooter className="mt-6 flex flex-row gap-2 justify-end">
                            <Button variant="ghost" onClick={onClose} className="text-slate-400">
                                Cancel
                            </Button>

                            {!generatedImage ? (
                                <Button
                                    onClick={handleGenerate}
                                    disabled={isGenerating || !prompt}
                                    className="bg-gradient-to-r from-yellow-500 to-orange-600 text-black font-bold hover:opacity-90"
                                >
                                    {isGenerating ? (
                                        <>
                                            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                                            Generating...
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles className="h-4 w-4 mr-2" />
                                            Generate
                                        </>
                                    )}
                                </Button>
                            ) : (
                                <div className="flex gap-2 w-full justify-end">
                                    <Button
                                        variant="outline"
                                        onClick={handleGenerate}
                                        disabled={isGenerating || isSaving}
                                        className="border-white/10 text-slate-300 hover:bg-white/5"
                                    >
                                        <RefreshCw className={cn("h-4 w-4 mr-2", isGenerating && "animate-spin")} />
                                        Retry
                                    </Button>
                                    <Button
                                        onClick={handleConfirm}
                                        disabled={isSaving}
                                        className="bg-blue-600 hover:bg-blue-700 text-white"
                                    >
                                        {isSaving ? (
                                            <>
                                                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                                                Saving...
                                            </>
                                        ) : (
                                            <>
                                                <Check className="h-4 w-4 mr-2" />
                                                Save Asset
                                            </>
                                        )}
                                    </Button>
                                </div>
                            )}
                        </DialogFooter>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
